<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeBehind="Joueurs.aspx.cs" Inherits="CRUD._Joueurs" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <div style="font-weight:bold">Create Joueur</div>
    <span style="height:20px; vertical-align:top">Nom :</span> 
    <asp:TextBox ID="txtJoueurName" runat="server"></asp:TextBox>

    <span style="height:20px; vertical-align:top">Prenom :</span> 
    <asp:TextBox ID="txtJoueurPrenom" runat="server"></asp:TextBox>

     <span style="height:20px; vertical-align:top">Sexe :</span> 
     <asp:RadioButton ID="rdSexe1"  GroupName="sexeg" runat="server" Text="Homme" />
     <asp:RadioButton ID="rdSexe2"   GroupName="sexeg"  runat="server" 
        Text="Femme" />
     
     <span style="height:20px; vertical-align:top">Equipe :</span> 
     <asp:DropDownList ID="ddlEquipe" runat="server" AutoPostBack="True">    
</asp:DropDownList>  

    <asp:Button ID="btnCreate" runat="server" Text="Enregistrer" 
    onclick="btnCreate_Click" />
    <hr />

    <hr />

    <div style="font-weight:bold">Search Joueur</div>
    <span style="height:20px; vertical-align:top">Joueur Name :</span>
    <asp:TextBox ID="txtSearchName" runat="server" Width="387px"></asp:TextBox>
    <asp:Button ID="btnSearch" runat="server" Text="Search" 
        onclick="btnSearch_Click" />
    <asp:GridView ID="gvJoueurList" runat="server" AllowPaging="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateSelectButton="True" GridLines="Vertical" 
        onrowcancelingedit="gvJoueurList_RowCancelingEdit" 
        onrowdeleting="gvJoueurList_RowDeleting" onrowediting="gvJoueurList_RowEditing" 
        onselectedindexchanged="gvJoueurList_SelectedIndexChanged" ShowFooter="True" 
         
        Width="648px" onrowdatabound="gvJoueurList_RowDataBound" 
        onrowupdating="gvJoueurList_RowUpdating">
        <Columns>
            <asp:TemplateField HeaderText="Equipe">
                   <EditItemTemplate>  
                        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>  
                    </EditItemTemplate>  
                    <ItemTemplate>  
                        <asp:DropDownList ID="ddequipeRow" runat="server">  
                        </asp:DropDownList>  
                    </ItemTemplate> 
            </asp:TemplateField>
             
        </Columns>
        <EditRowStyle BackColor="#FF3300" />
   

    </asp:GridView>
    <hr />
<div style="font-weight:bold"></div>
</asp:Content>
